language: python
python:
  - "3.6"
# command to install dependencies
cache: pip3
before_install:
  - pip install pytest
install:
  - 'pip install -r requirements.txt'
  - 'pip install -e .'
# command to run tests
script:
  - pytest
os: "linux"
dist: "trusty"
notifications:
    on_success: never
    on_failure: never